included:
  - SmartMachine/Sources
  - SmartMachineTests

disabled_rules:
  - line_length
  - type_body_length
  - identifier_name
  - type_name
  - weak_delegate
  - redundant_string_enum_value
  - notification_center_detachment
  - force_try
  - unused_closure_parameter

force_cast: warning

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 70
  error: 100
